services:
  drama_backend:
    container_name: drama_backend
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "7001:7001"
    environment:
      - DATABASE_URL=postgresql://postgres:rohiid123@db:5432/movie_db
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

  drama_frontend:
    container_name: drama_frontend
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "7000:80"
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - drama_backend
    networks:
      - app-network

  db:
    container_name: db
    image: postgres:16.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rohiid123
      POSTGRES_DB: movie_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
